### ISSUE TITLE
cookie warning

### ISSUE THREAD

**Issue by skylite21** [ElliottLandsborough/dog-ceo-api#20]
When fetching from the api with JS, the following message is displayed inside chrome console:

A cookie associated with a cross-site resource at http://dog.ceo/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

I could not find any way to resolve this from javascript. Here is a simple example code where this issue occurs. 

```
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test</title>
</head>
<body>
<div id="content"></div>
<script>
async function getResults(dogbreed) {
  const response = await fetch(`https://dog.ceo/api/breed/${dogbreed}/images`);
  const data = await response.json();
  const image = document.createElement('img');
  image.src = data.message[Math.floor(Math.random() * data.message.length)];
  document.querySelector('#content').appendChild(image);
}
getResults('papillon');
</script>
</body>
</html>
```

Is this something that can be resolved from the backend?

**Comment by ElliottLandsborough** [comment]
Hi @skylite21,

**Short answer**

This will be fixed by Cloudflare in the future but you don't need to worry about warnings, they won't stop the site from working and normal users will not see them. It is not fixable by either you or us.

**Long answer**

dog.ceo does not set any cookies when you make calls to the API.

We do use Cloudflare to aggressively cache our API responses so that we can continue to offer a fast and free service without having to pay high hosting costs.

Cloudflare does set a cookie which contains no personal data - at the moment it does not get sent with a 'SameSite' header which causes warnings in the newest chrome versions.

The cookie is called '__cfduid' which you will be able to find in your browser settings.

You can see the official Cloudflare response here: https://community.cloudflare.com/t/google-chrome-warning-about-cloudflare-cookie/123192/71

In the above thread it is mentioned that google recommend the issue is fixed by February 2020 as per this link: https://www.chromium.org/updates/same-site

Having said all of this, warnings are purely superficial and will not break the site for users. Annoying as it is when you are developing, there is nothing that can be done at this time.
