### ISSUE TITLE
Some dog images are inaccessible

### ISSUE THREAD

**Issue by giovanni-orciuolo** [ElliottLandsborough/dog-ceo-api#41]
Sometimes, even though the API returns `status === "success"`, the URL is inaccessible for some reason. A good solution would be a script that periodically checks the entire database and filters out inaccessible images.

**Comment by ElliottLandsborough** [comment]
There is quite a lot of caching to keep this service running for free which can lead to images not being available occasionally - for example if an image is removed or renamed it will take a while for the cache to catch up.

If you can provide an example where an image is not accessible I can have a look but I bet this is what the problem is.

**Comment by giovanni-orciuolo** [comment]
You are right, the problem is caused by cache. I can live with it
